"""Manual migration for initial tables

Revision ID: 18cee4698682
Revises: 
Create Date: 2024-11-23 19:47:26.512612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18cee4698682'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username')
    )
    # Add similar blocks for each of your tables (Quotes, Votes, Reports, Categories, etc.)
    # Example:
    op.create_table('quotes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('author', sa.String(), nullable=True),
        sa.Column('date_fetched', sa.Date(), nullable=False, default=sa.func.now()),
        sa.Column('submitted_by', sa.Integer(), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('is_community_qod', sa.Boolean(), nullable=True, default=False),
        sa.PrimaryKeyConstraint('id')
    )
    # Add other tables similarly
    # ### end Alembic commands ###

def downgrade():
    # Reverse the operations in the downgrade
    op.drop_table('quotes')
    op.drop_table('users')
    # Add drop table statements for each created table
